### PR TITLE
update screenshots

### PR DESCRIPTION
**Pull request by prestwick**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/systemlink-operations-handbook/blob/master/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/systemlink-operations-handbook/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Updates screenshots to current view of product in 2021R1

### Why should this Pull Request be merged?

Updated screenshots. 

### What testing has been done?

NA

### CODE REVIEW

**Review by JD-Robertson — CHANGES_REQUESTED** [review]
Need to fix the navigation URL for the ldap-login screenshot.

**Review by haworthia — CHANGES_REQUESTED** [review]
1. Is the idea to just use example.com in the navigation bar, or use example.com as the host? I am seeing it both ways, e.g. in allow-all-privileges.png it says "example.com/#/security/roles" and in claim-mapping.png it's just "https://example.com". I don't care which way we go, but it might be nice to be consistent.
2. Can we avoid having other product icons in the header bar? There's a pinned outlook tab, Systems Management somehow has a Microsoft logo, and there's this situation:
image

**Comment by JD-Robertson** [comment]
I assume there are NI standards for how we take screenshots for documentation. @jjaco2 can you provide guidance?

**Comment by jjaco2** [comment]
> I assume there are NI standards for how we take screenshots for documentation. @jjaco2 can you provide guidance?

@JD-Robertson I can't reply to your comment directly for some reason, but here are our [screenshot guidelines](https://niweb.natinst.com/confluence/display/PD/Art+Standards+for+Images+and+Screenshots). Only the stuff under "General Art Guidelines" could apply here. As you can see, they're pretty lax for anything that's not a screenshot of LabVIEW.

**Review by haworthia — APPROVED** [review]
Immaculate 👌

**Review by JD-Robertson — APPROVED** [review]
multiple-workspace.png has a real persons name in it. Probably a bad idea.

Also, all of the screenshots of the Workspaces view reference Grafana. Do we advertise integration with that product publicly?

**Pull request merged**
